// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_UpgxkPHErOk51jcEaEga96GNshv2e7s',
    appId: '1:391230991156:web:8acc964fa7b6daf57bd361',
    messagingSenderId: '391230991156',
    projectId: 'pedidos-pizzabrosa',
    authDomain: 'pedidos-pizzabrosa.firebaseapp.com',
    storageBucket: 'pedidos-pizzabrosa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJbc1vFg7myQ3D2GKO2Mi5Ed0lq23-YE',
    appId: '1:391230991156:android:43523cf5606abb047bd361',
    messagingSenderId: '391230991156',
    projectId: 'pedidos-pizzabrosa',
    storageBucket: 'pedidos-pizzabrosa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVgx270JqGqVqrVntpbWudVfPZe0rUdQ',
    appId: '1:391230991156:ios:cf63efed9c6538627bd361',
    messagingSenderId: '391230991156',
    projectId: 'pedidos-pizzabrosa',
    storageBucket: 'pedidos-pizzabrosa.firebasestorage.app',
    iosBundleId: 'com.example.pedidosPizzabrosa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLVgx270JqGqVqrVntpbWudVfPZe0rUdQ',
    appId: '1:391230991156:ios:cf63efed9c6538627bd361',
    messagingSenderId: '391230991156',
    projectId: 'pedidos-pizzabrosa',
    storageBucket: 'pedidos-pizzabrosa.firebasestorage.app',
    iosBundleId: 'com.example.pedidosPizzabrosa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_UpgxkPHErOk51jcEaEga96GNshv2e7s',
    appId: '1:391230991156:web:418cd0571c32bb5e7bd361',
    messagingSenderId: '391230991156',
    projectId: 'pedidos-pizzabrosa',
    authDomain: 'pedidos-pizzabrosa.firebaseapp.com',
    storageBucket: 'pedidos-pizzabrosa.firebasestorage.app',
  );
}
